DROP TABLE IF EXISTS temperature;

CREATE TABLE temperature (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lat FLOAT NOT NULL,
  lon FLOAT NOT NULL,
  temperature FLOAT NOT NULL,
  time TIMESTAMP NOT NULL
);